### PR TITLE
Fix mistake

### PR DESCRIPTION
**Pull request by kerrtravers**

### CODE REVIEW

**Review by Kenny2github — CHANGES_REQUESTED** [review]
While you're at it, could you also change "Hey, We're" to "Hey, we're" and "Your interested" to "You're interested"? Thanks.

**Comment by kerrtravers** [comment]
Done, but I sent another pr by mistake. #21

**Review by Kenny2github — DISMISSED** [review]
sigh... good to go then

**Review by Kenny2github — APPROVED** [review]
oops, other pr stale-ified my review

**Comment by kerrtravers** [comment]
👍

**Pull request merged**
