### PR TITLE
Fixes #24 | Make the header sticky

### LINKED ISSUE #24: Make the header sticky
### Feature
The header at the top of the page that says "Smelt: Batch Package Manager" (not the tab title) should be sticky (i.e. doesn't move when scrolling).
### Todo

- [ ] Make the header sticky
- [ ] Make sure it doesn't clash with anything, especially the top header
- [ ] Make sure it looks good overall

### PR DESCRIPTION
**Pull request by kerrtravers**
- [x] Make the header sticky
- [x] Make sure it doesn't clash with anything, especially the top header
- [x] Make sure it looks good overall

### CODE REVIEW

**Review by Kenny2github — CHANGES_REQUESTED** [review]
Problem: 
image
The header (yours above) is squashed compared to the original, below:
image

**Comment by kerrtravers** [comment]
Okay, I'll fix that 👍 

(I didn't know you wanted to have as much padding)

**Comment by Kenny2github** [comment]
No change:
image
You might need to use CSS style.height instead - brs won't work.

**Comment by vutondesign** [comment]
Fixed, Try clearing your cache.

**Review by Kenny2github — APPROVED** [review]

**Comment by kerrtravers** [comment]
👍

**Comment by Kenny2github** [comment]
@vutondesign might wanna delete your local branch

**Pull request merged**
